# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'crc_ui.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_mainWindow(object):
    def setupUi(self, mainWindow):
        mainWindow.setObjectName("mainWindow")
        mainWindow.resize(600, 250)
        mainWindow.setMinimumSize(QtCore.QSize(600, 250))
        mainWindow.setMaximumSize(QtCore.QSize(600, 250))
        mainWindow.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.centralwidget = QtWidgets.QWidget(mainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 10, 281, 91))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 4, 2, 1, 1)
        self.pushButton_welcome = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_welcome.sizePolicy().hasHeightForWidth())
        self.pushButton_welcome.setSizePolicy(sizePolicy)
        self.pushButton_welcome.setMaximumSize(QtCore.QSize(100, 20))
        self.pushButton_welcome.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_welcome.setObjectName("pushButton_welcome")
        self.gridLayout.addWidget(self.pushButton_welcome, 4, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 4, 0, 1, 1)
        self.lineEdit_welcome = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_welcome.setObjectName("lineEdit_welcome")
        self.gridLayout.addWidget(self.lineEdit_welcome, 1, 0, 1, 3)
        self.label_welcome = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_welcome.setObjectName("label_welcome")
        self.gridLayout.addWidget(self.label_welcome, 0, 0, 1, 3)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(160, 120, 271, 71))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_deciphered = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_deciphered.setObjectName("label_deciphered")
        self.verticalLayout_2.addWidget(self.label_deciphered)
        self.lineEdit_deciphered = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.lineEdit_deciphered.setObjectName("lineEdit_deciphered")
        self.verticalLayout_2.addWidget(self.lineEdit_deciphered)
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(310, 10, 281, 91))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_cipher = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_cipher.setObjectName("label_cipher")
        self.verticalLayout.addWidget(self.label_cipher)
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem2, 2, 0, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem3, 2, 2, 1, 1)
        self.lineEdit_cipher = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.lineEdit_cipher.setObjectName("lineEdit_cipher")
        self.gridLayout_3.addWidget(self.lineEdit_cipher, 0, 0, 1, 3)
        self.pushButton_cipher = QtWidgets.QPushButton(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_cipher.sizePolicy().hasHeightForWidth())
        self.pushButton_cipher.setSizePolicy(sizePolicy)
        self.pushButton_cipher.setMaximumSize(QtCore.QSize(100, 20))
        self.pushButton_cipher.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_cipher.setObjectName("pushButton_cipher")
        self.gridLayout_3.addWidget(self.pushButton_cipher, 2, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_3)
        mainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(mainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 600, 20))
        self.menubar.setObjectName("menubar")
        mainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(mainWindow)
        self.statusbar.setObjectName("statusbar")
        mainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(mainWindow)
        QtCore.QMetaObject.connectSlotsByName(mainWindow)

    def retranslateUi(self, mainWindow):
        _translate = QtCore.QCoreApplication.translate
        mainWindow.setWindowTitle(_translate("mainWindow", "MainWindow"))
        self.pushButton_welcome.setText(_translate("mainWindow", "Закодировать"))
        self.label_welcome.setText(_translate("mainWindow", "TextLabel"))
        self.label_deciphered.setText(_translate("mainWindow", "TextLabel"))
        self.label_cipher.setText(_translate("mainWindow", "TextLabel"))
        self.pushButton_cipher.setText(_translate("mainWindow", "Декодировать"))
