# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'rsa_signature_ui.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_mainWindow(object):
    def setupUi(self, mainWindow):
        mainWindow.setObjectName("mainWindow")
        mainWindow.resize(600, 600)
        mainWindow.setMinimumSize(QtCore.QSize(600, 600))
        mainWindow.setMaximumSize(QtCore.QSize(600, 600))
        mainWindow.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.centralwidget = QtWidgets.QWidget(mainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 10, 281, 121))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.lineEdit_pubkey = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_pubkey.setObjectName("lineEdit_pubkey")
        self.gridLayout.addWidget(self.lineEdit_pubkey, 1, 0, 1, 3)
        self.label_pubkey = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_pubkey.setObjectName("label_pubkey")
        self.gridLayout.addWidget(self.label_pubkey, 0, 0, 1, 3)
        self.pushButton_new_pubkey = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_new_pubkey.sizePolicy().hasHeightForWidth())
        self.pushButton_new_pubkey.setSizePolicy(sizePolicy)
        self.pushButton_new_pubkey.setMaximumSize(QtCore.QSize(20000, 20))
        self.pushButton_new_pubkey.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_new_pubkey.setObjectName("pushButton_new_pubkey")
        self.gridLayout.addWidget(self.pushButton_new_pubkey, 2, 0, 1, 3)
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(10, 140, 281, 301))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_input = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        self.label_input.setObjectName("label_input")
        self.verticalLayout_3.addWidget(self.label_input)
        self.textEdit_input = QtWidgets.QTextEdit(self.verticalLayoutWidget_3)
        self.textEdit_input.setObjectName("textEdit_input")
        self.verticalLayout_3.addWidget(self.textEdit_input)
        self.pushButton_encrypt = QtWidgets.QPushButton(self.verticalLayoutWidget_3)
        self.pushButton_encrypt.setObjectName("pushButton_encrypt")
        self.verticalLayout_3.addWidget(self.pushButton_encrypt)
        self.gridLayoutWidget_3 = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget_3.setGeometry(QtCore.QRect(300, 10, 281, 124))
        self.gridLayoutWidget_3.setObjectName("gridLayoutWidget_3")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.gridLayoutWidget_3)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_signature_in = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.label_signature_in.setObjectName("label_signature_in")
        self.gridLayout_4.addWidget(self.label_signature_in, 2, 0, 1, 2)
        self.label_pubkey_in = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.label_pubkey_in.setObjectName("label_pubkey_in")
        self.gridLayout_4.addWidget(self.label_pubkey_in, 0, 0, 1, 2)
        self.lineEdit_pubkey_in = QtWidgets.QLineEdit(self.gridLayoutWidget_3)
        self.lineEdit_pubkey_in.setObjectName("lineEdit_pubkey_in")
        self.gridLayout_4.addWidget(self.lineEdit_pubkey_in, 1, 0, 1, 2)
        self.lineEdit_signature_in = QtWidgets.QLineEdit(self.gridLayoutWidget_3)
        self.lineEdit_signature_in.setObjectName("lineEdit_signature_in")
        self.gridLayout_4.addWidget(self.lineEdit_signature_in, 3, 0, 1, 1)
        self.verticalLayoutWidget_4 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_4.setGeometry(QtCore.QRect(300, 140, 281, 301))
        self.verticalLayoutWidget_4.setObjectName("verticalLayoutWidget_4")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_4)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_output = QtWidgets.QLabel(self.verticalLayoutWidget_4)
        self.label_output.setObjectName("label_output")
        self.verticalLayout_4.addWidget(self.label_output)
        self.textEdit_output = QtWidgets.QTextEdit(self.verticalLayoutWidget_4)
        self.textEdit_output.setObjectName("textEdit_output")
        self.verticalLayout_4.addWidget(self.textEdit_output)
        self.pushButton_check = QtWidgets.QPushButton(self.verticalLayoutWidget_4)
        self.pushButton_check.setObjectName("pushButton_check")
        self.verticalLayout_4.addWidget(self.pushButton_check)
        self.label_result = QtWidgets.QLabel(self.centralwidget)
        self.label_result.setGeometry(QtCore.QRect(300, 460, 281, 51))
        self.label_result.setObjectName("label_result")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(10, 450, 279, 61))
        self.widget.setObjectName("widget")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.widget)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_signature = QtWidgets.QLabel(self.widget)
        self.label_signature.setObjectName("label_signature")
        self.gridLayout_3.addWidget(self.label_signature, 0, 0, 1, 2)
        self.lineEdit_signature = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_signature.setObjectName("lineEdit_signature")
        self.gridLayout_3.addWidget(self.lineEdit_signature, 1, 0, 1, 1)
        mainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(mainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 600, 20))
        self.menubar.setObjectName("menubar")
        mainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(mainWindow)
        self.statusbar.setObjectName("statusbar")
        mainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(mainWindow)
        QtCore.QMetaObject.connectSlotsByName(mainWindow)

    def retranslateUi(self, mainWindow):
        _translate = QtCore.QCoreApplication.translate
        mainWindow.setWindowTitle(_translate("mainWindow", "MainWindow"))
        self.label_pubkey.setText(_translate("mainWindow", "TextLabel"))
        self.pushButton_new_pubkey.setText(_translate("mainWindow", "Новый открытый ключ"))
        self.label_input.setText(_translate("mainWindow", "TextLabel"))
        self.pushButton_encrypt.setText(_translate("mainWindow", "Сгенерировать подпись"))
        self.label_signature_in.setText(_translate("mainWindow", "TextLabel"))
        self.label_pubkey_in.setText(_translate("mainWindow", "TextLabel"))
        self.label_output.setText(_translate("mainWindow", "TextLabel"))
        self.pushButton_check.setText(_translate("mainWindow", "Проверить подлинность"))
        self.label_result.setText(_translate("mainWindow", "TextLabel"))
        self.label_signature.setText(_translate("mainWindow", "TextLabel"))
